 services:
  web:
    build: .
    env_file:
      - .env          # Load environment variables from .env file
    volumes:
      - .:/app        # Mount the local directory into the container (for development)

